#!/usr/bin/python3
""" fetching the url statis using urllib"""
import urllib

if __name__ == "__main__":
    url = "https://alx-intranet.hbtn.io/status"
    with urlilib.request.urlopen(url) as answer:
     responce-body = answer.read()
     print("Body response:")
     print("- type: {}".format(type(responce-body)))
     print("- content: {}".format(responce-body))
     print("- utf8 content: {}".format(responce-body.decode("utf-8")))
